export const EMPLOYEE_LOGIN_FAIL = 'EMPLOYEE_LOGIN_FAIL';
export const EMPLOYEE_LOGIN_REQUEST = 'EMPLOYEE_LOGIN_REQUEST';
export const EMPLOYEE_LOGIN_SUCCESS = 'EMPLOYEE_LOGIN_SUCCESS';

export const EMPLOYEE_LOGIN_VERIFY_OTP_FAIL = "EMPLOYEE_LOGIN_VERIFY_OTP_FAIL";
export const EMPLOYEE_LOGIN_VERIFY_OTP_REQUEST = "EMPLOYEE_LOGIN_VERIFY_OTP_REQUEST";
export const EMPLOYEE_LOGIN_VERIFY_OTP_SUCCESS = "EMPLOYEE_LOGIN_VERIFY_OTP_SUCCESS";

export const EMPLOYEE_CAPTURE_MOBILE_FAIL = "EMPLOYEE_CAPTURE_MOBILE_FAIL";
export const EMPLOYEE_CAPTURE_MOBILE_REQUEST = "EMPLOYEE_CAPTURE_MOBILE_REQUEST";
export const EMPLOYEE_CAPTURE_MOBILE_SUCCESS = "EMPLOYEE_CAPTURE_MOBILE_SUCCESS";


export const EMPLOYEE_SIGNUP_FAIL = "EMPLOYEE_SIGNUP_FAIL";
export const EMPLOYEE_SIGNUP_REQUEST = "EMPLOYEE_SIGNUP_REQUEST";
export const EMPLOYEE_SIGNUP_SUCCESS = "EMPLOYEE_SIGNUP_SUCCESS";


export const EMPLOYEE_EMAIL_VERIFY_FAIL = "EMPLOYEE_EMAIL_VERIFY_FAIL";
export const EMPLOYEE_EMAIL_VERIFY_REQUEST = "EMPLOYEE_EMAIL_VERIFY_REQUEST";
export const EMPLOYEE_EMAIL_VERIFY_SUCCESS = "EMPLOYEE_EMAIL_VERIFY_SUCCESS";


export const EMPLOYEE_MOBILE_VERIFY_FAIL = "EMPLOYEE_MOBILE_VERIFY_FAIL";
export const EMPLOYEE_MOBILE_VERIFY_REQUEST = "EMPLOYEE_MOBILE_VERIFY_REQUEST";
export const EMPLOYEE_MOBILE_VERIFY_SUCCESS = "EMPLOYEE_MOBILE_VERIFY_SUCCESS";